### ISSUE TITLE
Initially loaded items in adapter

### ISSUE THREAD

**Issue by mohammadkhatri** [gabrielemariotti/RecyclerViewItemAnimators#5]
ItemAnimator works great when clicking Add and Remove buttons in sample project.
But can It be done on items which are initially loaded as in this project for listView and gridView. ?

https://github.com/nhaarman/ListViewAnimations

**Comment by Wavesonics** [comment]
+1

**Comment by gabrielemariotti** [comment]
The current ItemAnimator works with the add/remove/move events.
The initial loal is handled in a different way and requires some code on the adapter.

I am not sure that I will add this part in this library

**Comment by gabrielemariotti** [comment]
Updated with 0.3+

**Comment by mohammadkhatri** [comment]
Seems Impressive Now To me . Very Nice.
