### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by spierce7** [gabrielemariotti/RecyclerViewItemAnimators#6]
Are there any plans to update this now that RecyclerView has been released? Currently you're still requiring min sdk L.

This project also has been noticed by the community, and is currently the #1 search result on Google for RecyclerView ItemAnimator.

One more thing, as things are currently, this project doesn't need to be an Android Library, but could just be converted to a jar.

**Comment by gabrielemariotti** [comment]
#7

**Comment by gabrielemariotti** [comment]
Updated the code
