### ISSUE TITLE
Add Support for 23.1 App Compact 

### ISSUE THREAD

**Issue by vsahu1986** [gabrielemariotti/RecyclerViewItemAnimators#9]
Let the 
    
     public abstract class BaseItemAnimator extends SimpleItemAnimator 
instead of 
    
    public abstract class BaseItemAnimator extends RecyclerView.ItemAnimator

**Comment by gabrielemariotti** [comment]
Sorry for delay.
I will update the snapshot in maven in the next hours.

**Comment by gabrielemariotti** [comment]
Updated with 0.2+
